// Static seed data definitions for PathToSkill.
// Kept separate from seed.js (which handles DB insertion logic).

export const goals = [
  { title: 'Full-Stack Developer', slug: 'full-stack-developer', description: 'Build complete web applications across frontend and backend.' },
  { title: 'AI/ML Engineer', slug: 'ai-ml-engineer', description: 'Design and build machine learning and AI-powered systems.' },
  { title: 'Product Designer', slug: 'product-designer', description: 'Design usable, delightful digital products end to end.' },
  { title: 'Data Analyst', slug: 'data-analyst', description: 'Turn raw data into decisions through analysis and visualization.' },
  { title: 'Digital Marketing Specialist', slug: 'digital-marketing-specialist', description: 'Plan and run marketing campaigns across digital channels.' },
];

// category groups skills for filtering
export const skills = [
  // web
  { name: 'HTML', slug: 'html', category: 'Web' },
  { name: 'CSS', slug: 'css', category: 'Web' },
  { name: 'JavaScript', slug: 'javascript', category: 'Web' },
  { name: 'React', slug: 'react', category: 'Web' },
  { name: 'Node.js', slug: 'nodejs', category: 'Web' },
  { name: 'Express', slug: 'express', category: 'Web' },
  { name: 'PostgreSQL', slug: 'postgresql', category: 'Web' },
  { name: 'REST APIs', slug: 'rest-apis', category: 'Web' },
  { name: 'Full-Stack Development', slug: 'full-stack-development', category: 'Web' },
  // ai/ml
  { name: 'Python', slug: 'python', category: 'AI & Data' },
  { name: 'Statistics', slug: 'statistics', category: 'AI & Data' },
  { name: 'NumPy', slug: 'numpy', category: 'AI & Data' },
  { name: 'Pandas', slug: 'pandas', category: 'AI & Data' },
  { name: 'Machine Learning', slug: 'machine-learning', category: 'AI & Data' },
  { name: 'PyTorch', slug: 'pytorch', category: 'AI & Data' },
  { name: 'Deep Learning', slug: 'deep-learning', category: 'AI & Data' },
  { name: 'NLP', slug: 'nlp', category: 'AI & Data' },
  { name: 'Generative AI', slug: 'generative-ai', category: 'AI & Data' },
  // design
  { name: 'UX Design', slug: 'ux-design', category: 'Design' },
  { name: 'UI Design', slug: 'ui-design', category: 'Design' },
  { name: 'Figma', slug: 'figma', category: 'Design' },
  { name: 'User Research', slug: 'user-research', category: 'Design' },
  { name: 'Wireframing', slug: 'wireframing', category: 'Design' },
  { name: 'Prototyping', slug: 'prototyping', category: 'Design' },
  { name: 'Design Systems', slug: 'design-systems', category: 'Design' },
  { name: 'Usability Testing', slug: 'usability-testing', category: 'Design' },
  // data analytics
  { name: 'Excel', slug: 'excel', category: 'AI & Data' },
  { name: 'SQL', slug: 'sql', category: 'AI & Data' },
  { name: 'Data Cleaning', slug: 'data-cleaning', category: 'AI & Data' },
  { name: 'Power BI', slug: 'power-bi', category: 'AI & Data' },
  { name: 'Data Visualization', slug: 'data-visualization', category: 'AI & Data' },
  // marketing
  { name: 'Marketing', slug: 'marketing', category: 'Marketing' },
  { name: 'Content Marketing', slug: 'content-marketing', category: 'Marketing' },
  { name: 'SEO', slug: 'seo', category: 'Marketing' },
  { name: 'Social Media Marketing', slug: 'social-media-marketing', category: 'Marketing' },
  { name: 'Google Ads', slug: 'google-ads', category: 'Marketing' },
  { name: 'Email Marketing', slug: 'email-marketing', category: 'Marketing' },
  { name: 'Marketing Analytics', slug: 'marketing-analytics', category: 'Marketing' },
];

export const instructors = [
  { name: 'Maya Chen', title: 'Senior Full-Stack Engineer', bio: 'Ten years building web platforms; loves teaching JavaScript fundamentals.' },
  { name: 'Daniel Osei', title: 'Frontend Architect', bio: 'React specialist focused on component architecture and performance.' },
  { name: 'Priya Nair', title: 'Backend Engineer', bio: 'Node.js and distributed systems practitioner.' },
  { name: 'Tomas Novak', title: 'Database Engineer', bio: 'PostgreSQL and data modeling expert.' },
  { name: 'Sara Lindqvist', title: 'API Platform Lead', bio: 'Designs REST and GraphQL APIs used at scale.' },
  { name: 'Ahmed Farouk', title: 'ML Research Engineer', bio: 'Applies machine learning to real-world products.' },
  { name: 'Elena Rossi', title: 'Data Scientist', bio: 'Statistics and applied ML educator.' },
  { name: 'James Whitfield', title: 'Deep Learning Engineer', bio: 'PyTorch and neural network specialist.' },
  { name: 'Noor Haddad', title: 'NLP Researcher', bio: 'Works on language models and text understanding systems.' },
  { name: 'Lucas Ferreira', title: 'AI Product Engineer', bio: 'Builds generative AI applications end to end.' },
  { name: 'Grace Kim', title: 'Principal Product Designer', bio: 'Design systems and UX strategy across consumer products.' },
  { name: 'Oliver Bennett', title: 'UX Researcher', bio: 'User research methods for early-stage products.' },
  { name: 'Isabella Marino', title: 'UI/Figma Specialist', bio: 'Teaches interface design and prototyping in Figma.' },
  { name: 'Kenji Watanabe', title: 'Design Systems Lead', bio: 'Builds scalable design systems for product teams.' },
  { name: 'Fatima Al-Sayed', title: 'Data Analytics Manager', bio: 'Excel, SQL, and BI tooling for business teams.' },
  { name: 'Robert Klein', title: 'SQL & Database Instructor', bio: 'Teaches practical SQL for analytics roles.' },
  { name: 'Wei Zhang', title: 'BI Developer', bio: 'Power BI and dashboarding specialist.' },
  { name: 'Carla Mendes', title: 'Digital Marketing Strategist', bio: 'Runs multi-channel marketing campaigns for growing brands.' },
  { name: 'Tom Richards', title: 'SEO Consultant', bio: 'Search engine optimization and content strategy expert.' },
  { name: 'Aisha Bello', title: 'Paid Media Specialist', bio: 'Google Ads and paid acquisition expert.' },
];

// Courses grouped by the journey they primarily belong to, with skills, difficulty, hours.
// instructor referenced by name (resolved to id during seeding)
export const courses = [
  // Full-Stack
  { title: 'HTML & CSS Fundamentals', slug: 'html-css-fundamentals', category: 'Web Development', difficulty: 'beginner', duration_hours: 12, price: 0, instructor: 'Maya Chen', skills: ['HTML', 'CSS'], learning_outcomes: ['Structure semantic web pages', 'Style responsive layouts with CSS', 'Understand the box model and flexbox'], project_count: 1, video: { url: 'https://www.youtube.com/watch?v=mU6anWqZJcc', provider: 'freeCodeCamp.org', durationMinutes: 690 } },
  { title: 'JavaScript Fundamentals', slug: 'javascript-fundamentals', category: 'Web Development', difficulty: 'beginner', duration_hours: 18, price: 0, instructor: 'Maya Chen', skills: ['JavaScript'], learning_outcomes: ['Write functions, loops, and conditionals', 'Manipulate the DOM', 'Understand asynchronous JavaScript'], project_count: 1, video: { url: 'https://www.youtube.com/watch?v=PkZNo7MFNFg', provider: 'freeCodeCamp.org', durationMinutes: 210 } },
  { title: 'React for Beginners', slug: 'react-for-beginners', category: 'Web Development', difficulty: 'beginner', duration_hours: 20, price: 29, instructor: 'Daniel Osei', skills: ['React', 'JavaScript'], learning_outcomes: ['Build components with JSX', 'Manage state and props', 'Handle events and forms'], project_count: 1, video: { url: 'https://www.youtube.com/watch?v=DLX62G4lc44', provider: 'freeCodeCamp.org', durationMinutes: 300 } },
  { title: 'Advanced React & Frontend Development', slug: 'advanced-react-frontend', category: 'Web Development', difficulty: 'intermediate', duration_hours: 24, price: 39, instructor: 'Daniel Osei', skills: ['React'], learning_outcomes: ['Use hooks effectively', 'Manage complex application state', 'Optimize rendering performance'], project_count: 1 },
  { title: 'Node.js & Express', slug: 'nodejs-express', category: 'Web Development', difficulty: 'intermediate', duration_hours: 22, price: 39, instructor: 'Priya Nair', skills: ['Node.js', 'Express'], learning_outcomes: ['Build server-side applications', 'Create middleware and routing', 'Handle authentication basics'], project_count: 1, video: { url: 'https://www.youtube.com/watch?v=Oe421EPjeBE', provider: 'freeCodeCamp.org', durationMinutes: 480 } },
  { title: 'PostgreSQL Fundamentals', slug: 'postgresql-fundamentals', category: 'Web Development', difficulty: 'intermediate', duration_hours: 16, price: 29, instructor: 'Tomas Novak', skills: ['PostgreSQL'], learning_outcomes: ['Design relational schemas', 'Write SQL queries and joins', 'Use indexes and constraints'], project_count: 0, video: { url: 'https://www.youtube.com/watch?v=SpfIwlAYaKk', provider: 'freeCodeCamp.org', durationMinutes: 180 } },
  { title: 'REST API Development', slug: 'rest-api-development', category: 'Web Development', difficulty: 'intermediate', duration_hours: 18, price: 39, instructor: 'Sara Lindqvist', skills: ['REST APIs', 'Node.js'], learning_outcomes: ['Design RESTful endpoints', 'Handle authentication and validation', 'Document and test APIs'], project_count: 1, video: { url: 'https://www.youtube.com/watch?v=WXsD0ZgxjRw', provider: 'freeCodeCamp.org (Twilio)', durationMinutes: 180 } },
  { title: 'Building Full-Stack Applications', slug: 'building-full-stack-applications', category: 'Web Development', difficulty: 'advanced', duration_hours: 30, price: 49, instructor: 'Sara Lindqvist', skills: ['Full-Stack Development', 'React', 'Node.js', 'PostgreSQL'], learning_outcomes: ['Connect frontend to backend end to end', 'Deploy a full-stack application', 'Structure a production-ready codebase'], project_count: 1 },

  // AI/ML
  { title: 'Python for Data Science', slug: 'python-for-data-science', category: 'AI & Machine Learning', difficulty: 'beginner', duration_hours: 16, price: 0, instructor: 'Ahmed Farouk', skills: ['Python'], learning_outcomes: ['Write Python for data tasks', 'Use core data structures', 'Work with scripts and notebooks'], project_count: 0, video: { url: 'https://www.youtube.com/watch?v=CMEWVn1uZpQ', provider: 'freeCodeCamp.org', durationMinutes: 1020 } },
  { title: 'Statistics for Machine Learning', slug: 'statistics-for-machine-learning', category: 'AI & Machine Learning', difficulty: 'beginner', duration_hours: 14, price: 0, instructor: 'Elena Rossi', skills: ['Statistics'], learning_outcomes: ['Understand distributions and probability', 'Apply hypothesis testing', 'Interpret statistical significance'], project_count: 0 },
  { title: 'NumPy & Pandas', slug: 'numpy-pandas', category: 'AI & Machine Learning', difficulty: 'beginner', duration_hours: 14, price: 19, instructor: 'Elena Rossi', skills: ['NumPy', 'Pandas'], learning_outcomes: ['Manipulate arrays and dataframes', 'Clean and transform datasets', 'Perform exploratory data analysis'], project_count: 0 },
  { title: 'Machine Learning Fundamentals', slug: 'machine-learning-fundamentals', category: 'AI & Machine Learning', difficulty: 'intermediate', duration_hours: 26, price: 39, instructor: 'Ahmed Farouk', skills: ['Machine Learning'], learning_outcomes: ['Train supervised learning models', 'Evaluate model performance', 'Avoid overfitting with validation'], project_count: 1 },
  { title: 'Deep Learning with PyTorch', slug: 'deep-learning-pytorch', category: 'AI & Machine Learning', difficulty: 'intermediate', duration_hours: 28, price: 49, instructor: 'James Whitfield', skills: ['PyTorch', 'Deep Learning'], learning_outcomes: ['Build neural networks in PyTorch', 'Train and tune deep learning models', 'Use GPUs for training'], project_count: 1 },
  { title: 'Natural Language Processing', slug: 'natural-language-processing', category: 'AI & Machine Learning', difficulty: 'advanced', duration_hours: 24, price: 49, instructor: 'Noor Haddad', skills: ['NLP'], learning_outcomes: ['Process and tokenize text', 'Build text classification models', 'Understand transformer architectures'], project_count: 0 },
  { title: 'Generative AI Fundamentals', slug: 'generative-ai-fundamentals', category: 'AI & Machine Learning', difficulty: 'advanced', duration_hours: 20, price: 49, instructor: 'Lucas Ferreira', skills: ['Generative AI'], learning_outcomes: ['Understand large language models', 'Use prompting techniques effectively', 'Build applications with generative AI APIs'], project_count: 1 },
  { title: 'AI Capstone', slug: 'ai-capstone', category: 'AI & Machine Learning', difficulty: 'advanced', duration_hours: 30, price: 59, instructor: 'Lucas Ferreira', skills: ['Machine Learning', 'Generative AI'], learning_outcomes: ['Combine ML skills into a capstone project', 'Deploy a working AI application', 'Present technical results clearly'], project_count: 1 },

  // Product Design
  { title: 'Design Fundamentals', slug: 'design-fundamentals', category: 'Product Design', difficulty: 'beginner', duration_hours: 10, price: 0, instructor: 'Grace Kim', skills: ['UI Design'], learning_outcomes: ['Understand core visual design principles', 'Apply color, type, and layout', 'Critique design work constructively'], project_count: 0 },
  { title: 'Introduction to UX', slug: 'introduction-to-ux', category: 'Product Design', difficulty: 'beginner', duration_hours: 12, price: 0, instructor: 'Oliver Bennett', skills: ['UX Design'], learning_outcomes: ['Understand the UX design process', 'Map user journeys', 'Identify usability problems'], project_count: 0 },
  { title: 'User Research', slug: 'user-research', category: 'Product Design', difficulty: 'beginner', duration_hours: 12, price: 19, instructor: 'Oliver Bennett', skills: ['User Research'], learning_outcomes: ['Plan and conduct user interviews', 'Synthesize research findings', 'Build personas and journey maps'], project_count: 0 },
  { title: 'Figma Fundamentals', slug: 'figma-fundamentals', category: 'Product Design', difficulty: 'beginner', duration_hours: 14, price: 19, instructor: 'Isabella Marino', skills: ['Figma'], learning_outcomes: ['Navigate the Figma interface', 'Build components and auto layout', 'Collaborate in real time'], project_count: 0 },
  { title: 'Wireframing & Prototyping', slug: 'wireframing-prototyping', category: 'Product Design', difficulty: 'intermediate', duration_hours: 16, price: 29, instructor: 'Isabella Marino', skills: ['Wireframing', 'Prototyping'], learning_outcomes: ['Create low and high fidelity wireframes', 'Build interactive prototypes', 'Test flows before development'], project_count: 1 },
  { title: 'Design Systems', slug: 'design-systems', category: 'Product Design', difficulty: 'intermediate', duration_hours: 18, price: 39, instructor: 'Kenji Watanabe', skills: ['Design Systems'], learning_outcomes: ['Build reusable component libraries', 'Establish design tokens', 'Maintain consistency at scale'], project_count: 0 },
  { title: 'Usability Testing', slug: 'usability-testing', category: 'Product Design', difficulty: 'intermediate', duration_hours: 12, price: 29, instructor: 'Oliver Bennett', skills: ['Usability Testing'], learning_outcomes: ['Design usability test scripts', 'Run moderated tests', 'Turn findings into design changes'], project_count: 0 },
  { title: 'Product Design Portfolio', slug: 'product-design-portfolio', category: 'Product Design', difficulty: 'advanced', duration_hours: 20, price: 39, instructor: 'Grace Kim', skills: ['UX Design', 'UI Design'], learning_outcomes: ['Curate strong case studies', 'Present design decisions clearly', 'Build a hireable portfolio'], project_count: 1 },

  // Data Analytics
  { title: 'Advanced Excel', slug: 'advanced-excel', category: 'Data Analytics', difficulty: 'beginner', duration_hours: 12, price: 0, instructor: 'Fatima Al-Sayed', skills: ['Excel'], learning_outcomes: ['Use advanced formulas and pivot tables', 'Build dynamic spreadsheets', 'Automate repetitive analysis'], project_count: 0 },
  { title: 'SQL Fundamentals', slug: 'sql-fundamentals', category: 'Data Analytics', difficulty: 'beginner', duration_hours: 16, price: 0, instructor: 'Robert Klein', skills: ['SQL'], learning_outcomes: ['Write SELECT queries with joins', 'Aggregate and filter data', 'Understand relational database basics'], project_count: 0 },
  { title: 'Data Cleaning', slug: 'data-cleaning', category: 'Data Analytics', difficulty: 'beginner', duration_hours: 10, price: 19, instructor: 'Fatima Al-Sayed', skills: ['Data Cleaning'], learning_outcomes: ['Identify and fix data quality issues', 'Standardize messy datasets', 'Prepare data for analysis'], project_count: 0 },
  { title: 'Statistics for Data Analysis', slug: 'statistics-for-data-analysis', category: 'Data Analytics', difficulty: 'intermediate', duration_hours: 14, price: 19, instructor: 'Elena Rossi', skills: ['Statistics'], learning_outcomes: ['Summarize data with descriptive statistics', 'Apply correlation and regression', 'Interpret analytical results'], project_count: 0 },
  { title: 'Python for Data Analysis', slug: 'python-for-data-analysis', category: 'Data Analytics', difficulty: 'intermediate', duration_hours: 18, price: 29, instructor: 'Ahmed Farouk', skills: ['Python', 'Pandas'], learning_outcomes: ['Use Python for analysis workflows', 'Automate reporting with pandas', 'Combine and reshape datasets'], project_count: 1 },
  { title: 'Power BI Fundamentals', slug: 'power-bi-fundamentals', category: 'Data Analytics', difficulty: 'intermediate', duration_hours: 16, price: 29, instructor: 'Wei Zhang', skills: ['Power BI'], learning_outcomes: ['Build interactive dashboards', 'Model relationships between tables', 'Publish and share reports'], project_count: 1 },
  { title: 'Data Visualization', slug: 'data-visualization', category: 'Data Analytics', difficulty: 'intermediate', duration_hours: 14, price: 29, instructor: 'Wei Zhang', skills: ['Data Visualization'], learning_outcomes: ['Choose the right chart for the data', 'Design clear, honest visualizations', 'Tell a story with data'], project_count: 0 },
  { title: 'Business Analytics Capstone', slug: 'business-analytics-capstone', category: 'Data Analytics', difficulty: 'advanced', duration_hours: 24, price: 39, instructor: 'Fatima Al-Sayed', skills: ['SQL', 'Power BI', 'Data Visualization'], learning_outcomes: ['Deliver an end-to-end analytics project', 'Present insights to stakeholders', 'Build a portfolio-ready dashboard'], project_count: 1 },

  // Digital Marketing
  { title: 'Marketing Fundamentals', slug: 'marketing-fundamentals', category: 'Digital Marketing', difficulty: 'beginner', duration_hours: 10, price: 0, instructor: 'Carla Mendes', skills: ['Marketing'], learning_outcomes: ['Understand core marketing principles', 'Identify target audiences', 'Build a basic marketing plan'], project_count: 0 },
  { title: 'Content Marketing', slug: 'content-marketing', category: 'Digital Marketing', difficulty: 'beginner', duration_hours: 12, price: 0, instructor: 'Carla Mendes', skills: ['Content Marketing'], learning_outcomes: ['Plan a content calendar', 'Write for different channels', 'Measure content performance'], project_count: 0 },
  { title: 'SEO Fundamentals', slug: 'seo-fundamentals', category: 'Digital Marketing', difficulty: 'beginner', duration_hours: 14, price: 19, instructor: 'Tom Richards', skills: ['SEO'], learning_outcomes: ['Perform keyword research', 'Optimize on-page content', 'Understand technical SEO basics'], project_count: 1 },
  { title: 'Social Media Marketing', slug: 'social-media-marketing', category: 'Digital Marketing', difficulty: 'intermediate', duration_hours: 14, price: 19, instructor: 'Carla Mendes', skills: ['Social Media Marketing'], learning_outcomes: ['Build a social content strategy', 'Grow engagement organically', 'Analyze social performance'], project_count: 1 },
  { title: 'Google Ads', slug: 'google-ads', category: 'Digital Marketing', difficulty: 'intermediate', duration_hours: 16, price: 29, instructor: 'Aisha Bello', skills: ['Google Ads'], learning_outcomes: ['Set up search and display campaigns', 'Manage budgets and bidding', 'Optimize ad performance'], project_count: 0 },
  { title: 'Email Marketing', slug: 'email-marketing', category: 'Digital Marketing', difficulty: 'intermediate', duration_hours: 10, price: 19, instructor: 'Carla Mendes', skills: ['Email Marketing'], learning_outcomes: ['Build automated email flows', 'Segment audiences effectively', 'Improve open and click rates'], project_count: 0 },
  { title: 'Marketing Analytics', slug: 'marketing-analytics', category: 'Digital Marketing', difficulty: 'intermediate', duration_hours: 14, price: 29, instructor: 'Aisha Bello', skills: ['Marketing Analytics'], learning_outcomes: ['Track campaign performance', 'Build marketing dashboards', 'Make data-informed decisions'], project_count: 0 },
  { title: 'Digital Marketing Campaign', slug: 'digital-marketing-campaign', category: 'Digital Marketing', difficulty: 'advanced', duration_hours: 20, price: 39, instructor: 'Tom Richards', skills: ['SEO', 'Social Media Marketing', 'Marketing Analytics'], learning_outcomes: ['Plan a full multi-channel campaign', 'Coordinate content, ads, and email', 'Report on campaign outcomes'], project_count: 1 },
];

export const projects = [
  { title: 'Personal Portfolio', slug: 'personal-portfolio', description: 'Build and deploy a personal portfolio site showcasing your work using HTML, CSS, and JavaScript.', difficulty: 'beginner', estimated_hours: 8, skills: ['HTML', 'CSS', 'JavaScript'], relatedCourses: ['html-css-fundamentals', 'javascript-fundamentals'] },
  { title: 'Task Management Application', slug: 'task-management-application', description: 'Create a React task manager with filtering, sorting, and persistent state.', difficulty: 'intermediate', estimated_hours: 14, skills: ['React', 'JavaScript'], relatedCourses: ['react-for-beginners', 'advanced-react-frontend'] },
  { title: 'Full-Stack E-commerce Application', slug: 'full-stack-ecommerce-application', description: 'Build a complete e-commerce app with a React frontend, Express API, and PostgreSQL database.', difficulty: 'advanced', estimated_hours: 30, skills: ['React', 'Node.js', 'PostgreSQL', 'REST APIs'], relatedCourses: ['building-full-stack-applications', 'rest-api-development'] },

  { title: 'House Price Prediction Model', slug: 'house-price-prediction-model', description: 'Train a regression model to predict housing prices from structured data.', difficulty: 'intermediate', estimated_hours: 12, skills: ['Python', 'Machine Learning'], relatedCourses: ['machine-learning-fundamentals', 'numpy-pandas'] },
  { title: 'Image Classification Model', slug: 'image-classification-model', description: 'Build and train a convolutional neural network to classify images using PyTorch.', difficulty: 'advanced', estimated_hours: 18, skills: ['PyTorch', 'Deep Learning'], relatedCourses: ['deep-learning-pytorch'] },
  { title: 'AI Question Answering Application', slug: 'ai-question-answering-application', description: 'Build an application that answers questions over a custom document set using generative AI.', difficulty: 'advanced', estimated_hours: 20, skills: ['Generative AI', 'NLP'], relatedCourses: ['generative-ai-fundamentals', 'natural-language-processing'] },

  { title: 'Mobile Banking App Redesign', slug: 'mobile-banking-app-redesign', description: 'Redesign a mobile banking flow with improved usability and visual clarity.', difficulty: 'intermediate', estimated_hours: 14, skills: ['UX Design', 'Figma'], relatedCourses: ['figma-fundamentals', 'wireframing-prototyping'] },
  { title: 'E-commerce Checkout Redesign', slug: 'ecommerce-checkout-redesign', description: 'Redesign an e-commerce checkout flow to reduce drop-off and confusion.', difficulty: 'intermediate', estimated_hours: 12, skills: ['UX Design', 'Prototyping'], relatedCourses: ['wireframing-prototyping', 'usability-testing'] },
  { title: 'SaaS Product Design', slug: 'saas-product-design', description: 'Design a complete SaaS dashboard experience with a reusable design system.', difficulty: 'advanced', estimated_hours: 20, skills: ['UI Design', 'Design Systems'], relatedCourses: ['design-systems', 'product-design-portfolio'] },

  { title: 'Sales Performance Dashboard', slug: 'sales-performance-dashboard', description: 'Build an Excel/SQL-driven dashboard analyzing sales performance trends.', difficulty: 'beginner', estimated_hours: 10, skills: ['Excel', 'SQL'], relatedCourses: ['advanced-excel', 'sql-fundamentals'] },
  { title: 'Customer Churn Analysis', slug: 'customer-churn-analysis', description: 'Analyze customer data with Python to identify drivers of churn.', difficulty: 'intermediate', estimated_hours: 14, skills: ['Python', 'Statistics'], relatedCourses: ['python-for-data-analysis', 'statistics-for-data-analysis'] },
  { title: 'Business Intelligence Dashboard', slug: 'business-intelligence-dashboard', description: 'Design an end-to-end BI dashboard in Power BI from raw business data.', difficulty: 'advanced', estimated_hours: 18, skills: ['Power BI', 'Data Visualization'], relatedCourses: ['power-bi-fundamentals', 'business-analytics-capstone'] },

  { title: 'SEO Strategy', slug: 'seo-strategy', description: 'Develop a complete SEO strategy and content plan for a sample business.', difficulty: 'beginner', estimated_hours: 8, skills: ['SEO'], relatedCourses: ['seo-fundamentals'] },
  { title: 'Social Media Campaign', slug: 'social-media-campaign', description: 'Plan and execute a multi-platform social media campaign with performance tracking.', difficulty: 'intermediate', estimated_hours: 12, skills: ['Social Media Marketing'], relatedCourses: ['social-media-marketing'] },
  { title: 'Complete Digital Marketing Campaign', slug: 'complete-digital-marketing-campaign', description: 'Plan, launch, and analyze a full multi-channel digital marketing campaign.', difficulty: 'advanced', estimated_hours: 20, skills: ['SEO', 'Social Media Marketing', 'Marketing Analytics'], relatedCourses: ['digital-marketing-campaign'] },
];

// The five seeded successful learner journeys.
export const journeys = [
  {
    title: 'Full-Stack Development Journey',
    slug: 'full-stack-development-journey',
    goal: 'Full-Stack Developer',
    learner_label: 'Learner Journey #01',
    demoLearner: { name: 'Aarav', email: 'aarav.demo@pathtoskill.example' },
    starting_level: 'beginner',
    startingSkills: ['JavaScript', 'HTML', 'CSS'],
    startingSkillLabels: { JavaScript: 'Basic JavaScript', HTML: 'Basic HTML', CSS: 'Basic CSS' },
    outcome: 'Junior Full-Stack Developer',
    duration_weeks: 20,
    description: 'A steady path from web fundamentals to a complete full-stack application, built one layer at a time.',
    steps: [
      { phase: 'FOUNDATIONS', title: 'HTML & CSS Fundamentals', skill: 'HTML' },
      { phase: 'FOUNDATIONS', title: 'JavaScript Fundamentals', skill: 'JavaScript' },
      { phase: 'FRONTEND', title: 'React for Beginners', skill: 'React' },
      { phase: 'FRONTEND', title: 'Advanced React & Frontend Development', skill: 'React' },
      { phase: 'BACKEND', title: 'Node.js & Express', skill: 'Node.js' },
      { phase: 'BACKEND', title: 'PostgreSQL & Database Fundamentals', skill: 'PostgreSQL' },
      { phase: 'BACKEND', title: 'REST API Development', skill: 'REST APIs' },
      { phase: 'PROJECTS', title: 'Full-Stack Project', skill: 'Full-Stack Development' },
    ],
    courseSlugs: ['html-css-fundamentals', 'javascript-fundamentals', 'react-for-beginners', 'advanced-react-frontend', 'nodejs-express', 'postgresql-fundamentals', 'rest-api-development', 'building-full-stack-applications'],
    projectSlugs: ['personal-portfolio', 'task-management-application', 'full-stack-ecommerce-application'],
    // Personal Portfolio right after HTML/CSS+JS; Task Management App after React is covered;
    // the full e-commerce build caps the journey off at the very end (null = after last course).
    projectPlacement: { 'personal-portfolio': 2, 'task-management-application': 4, 'full-stack-ecommerce-application': null },
    skillsGained: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js', 'Express', 'PostgreSQL', 'REST APIs', 'Full-Stack Development'],
  },
  {
    title: 'AI & Machine Learning Journey',
    slug: 'ai-machine-learning-journey',
    goal: 'AI/ML Engineer',
    learner_label: 'Learner Journey #02',
    demoLearner: { name: 'Meera', email: 'meera.demo@pathtoskill.example' },
    starting_level: 'beginner',
    startingSkills: ['Python', 'Statistics'],
    startingSkillLabels: { Python: 'Basic Python', Statistics: 'Basic Mathematics' },
    outcome: 'Machine Learning / AI Developer',
    duration_weeks: 24,
    description: 'From Python basics to building and shipping a generative AI application.',
    steps: [
      { phase: 'FOUNDATIONS', title: 'Python for Data Science', skill: 'Python' },
      { phase: 'FOUNDATIONS', title: 'Statistics for Machine Learning', skill: 'Statistics' },
      { phase: 'DATA', title: 'NumPy & Pandas', skill: 'Pandas' },
      { phase: 'MACHINE LEARNING', title: 'Machine Learning Fundamentals', skill: 'Machine Learning' },
      { phase: 'MACHINE LEARNING', title: 'Deep Learning with PyTorch', skill: 'PyTorch' },
      { phase: 'MACHINE LEARNING', title: 'Natural Language Processing', skill: 'NLP' },
      { phase: 'ADVANCED AI', title: 'Generative AI Fundamentals', skill: 'Generative AI' },
      { phase: 'PROJECTS', title: 'AI Capstone Project', skill: 'Generative AI' },
    ],
    courseSlugs: ['python-for-data-science', 'statistics-for-machine-learning', 'numpy-pandas', 'machine-learning-fundamentals', 'deep-learning-pytorch', 'natural-language-processing', 'generative-ai-fundamentals', 'ai-capstone'],
    projectSlugs: ['house-price-prediction-model', 'image-classification-model', 'ai-question-answering-application'],
    projectPlacement: { 'house-price-prediction-model': 4, 'image-classification-model': 5, 'ai-question-answering-application': null },
    skillsGained: ['Python', 'Statistics', 'NumPy', 'Pandas', 'Machine Learning', 'PyTorch', 'Deep Learning', 'NLP', 'Generative AI'],
  },
  {
    title: 'Product Design Journey',
    slug: 'product-design-journey',
    goal: 'Product Designer',
    learner_label: 'Learner Journey #03',
    demoLearner: { name: 'Anika', email: 'anika.demo@pathtoskill.example' },
    starting_level: 'beginner',
    startingSkills: ['UI Design'],
    startingSkillLabels: { 'UI Design': 'Basic design knowledge' },
    outcome: 'Junior Product Designer',
    duration_weeks: 18,
    description: 'From visual design basics to a complete, research-backed product design portfolio.',
    steps: [
      { phase: 'FOUNDATIONS', title: 'Design Fundamentals', skill: 'UI Design' },
      { phase: 'RESEARCH', title: 'User Research', skill: 'User Research' },
      { phase: 'RESEARCH', title: 'UX Design Principles', skill: 'UX Design' },
      { phase: 'TOOLING', title: 'Figma Fundamentals', skill: 'Figma' },
      { phase: 'TOOLING', title: 'Wireframing & Prototyping', skill: 'Wireframing' },
      { phase: 'SYSTEMS', title: 'Design Systems', skill: 'Design Systems' },
      { phase: 'VALIDATION', title: 'Usability Testing', skill: 'Usability Testing' },
      { phase: 'PROJECTS', title: 'Product Design Portfolio', skill: 'UI Design' },
    ],
    courseSlugs: ['design-fundamentals', 'introduction-to-ux', 'user-research', 'figma-fundamentals', 'wireframing-prototyping', 'design-systems', 'usability-testing', 'product-design-portfolio'],
    projectSlugs: ['mobile-banking-app-redesign', 'ecommerce-checkout-redesign', 'saas-product-design'],
    projectPlacement: { 'mobile-banking-app-redesign': 5, 'ecommerce-checkout-redesign': 7, 'saas-product-design': null },
    skillsGained: ['UX Design', 'UI Design', 'Figma', 'User Research', 'Wireframing', 'Prototyping', 'Design Systems', 'Usability Testing'],
  },
  {
    title: 'Data Analytics Journey',
    slug: 'data-analytics-journey',
    goal: 'Data Analyst',
    learner_label: 'Learner Journey #04',
    demoLearner: { name: 'Rohan', email: 'rohan.demo@pathtoskill.example' },
    starting_level: 'beginner',
    startingSkills: ['Excel'],
    startingSkillLabels: { Excel: 'Basic Excel' },
    outcome: 'Junior Data Analyst',
    duration_weeks: 16,
    description: 'From spreadsheets to a full business intelligence dashboard, built on real analysis skills.',
    steps: [
      { phase: 'FOUNDATIONS', title: 'Advanced Excel', skill: 'Excel' },
      { phase: 'FOUNDATIONS', title: 'SQL Fundamentals', skill: 'SQL' },
      { phase: 'DATA PREP', title: 'Data Cleaning', skill: 'Data Cleaning' },
      { phase: 'ANALYSIS', title: 'Statistics for Data Analysis', skill: 'Statistics' },
      { phase: 'ANALYSIS', title: 'Python for Data Analysis', skill: 'Python' },
      { phase: 'VISUALIZATION', title: 'Power BI', skill: 'Power BI' },
      { phase: 'VISUALIZATION', title: 'Data Visualization', skill: 'Data Visualization' },
      { phase: 'PROJECTS', title: 'Analytics Capstone', skill: 'Data Visualization' },
    ],
    courseSlugs: ['advanced-excel', 'sql-fundamentals', 'data-cleaning', 'statistics-for-data-analysis', 'python-for-data-analysis', 'power-bi-fundamentals', 'data-visualization', 'business-analytics-capstone'],
    projectSlugs: ['sales-performance-dashboard', 'customer-churn-analysis', 'business-intelligence-dashboard'],
    projectPlacement: { 'sales-performance-dashboard': 2, 'customer-churn-analysis': 5, 'business-intelligence-dashboard': null },
    skillsGained: ['Excel', 'SQL', 'Data Cleaning', 'Statistics', 'Python', 'Pandas', 'Power BI', 'Data Visualization'],
  },
  {
    title: 'Digital Marketing Journey',
    slug: 'digital-marketing-journey',
    goal: 'Digital Marketing Specialist',
    learner_label: 'Learner Journey #05',
    demoLearner: { name: 'Kabir', email: 'kabir.demo@pathtoskill.example' },
    starting_level: 'beginner',
    startingSkills: ['Marketing', 'Social Media Marketing'],
    startingSkillLabels: { Marketing: 'Basic marketing knowledge', 'Social Media Marketing': 'Social media familiarity' },
    outcome: 'Digital Marketing Specialist',
    duration_weeks: 14,
    description: 'From core marketing principles to running a full multi-channel campaign.',
    steps: [
      { phase: 'FOUNDATIONS', title: 'Marketing Fundamentals', skill: 'Marketing' },
      { phase: 'CONTENT', title: 'Content Marketing', skill: 'Content Marketing' },
      { phase: 'CONTENT', title: 'SEO Fundamentals', skill: 'SEO' },
      { phase: 'CHANNELS', title: 'Social Media Marketing', skill: 'Social Media Marketing' },
      { phase: 'CHANNELS', title: 'Google Ads', skill: 'Google Ads' },
      { phase: 'CHANNELS', title: 'Email Marketing', skill: 'Email Marketing' },
      { phase: 'ANALYTICS', title: 'Marketing Analytics', skill: 'Marketing Analytics' },
      { phase: 'PROJECTS', title: 'Digital Marketing Campaign', skill: 'Marketing Analytics' },
    ],
    courseSlugs: ['marketing-fundamentals', 'content-marketing', 'seo-fundamentals', 'social-media-marketing', 'google-ads', 'email-marketing', 'marketing-analytics', 'digital-marketing-campaign'],
    projectSlugs: ['seo-strategy', 'social-media-campaign', 'complete-digital-marketing-campaign'],
    projectPlacement: { 'seo-strategy': 3, 'social-media-campaign': 4, 'complete-digital-marketing-campaign': null },
    skillsGained: ['Marketing', 'Content Marketing', 'SEO', 'Social Media Marketing', 'Google Ads', 'Email Marketing', 'Marketing Analytics'],
  },
];

export const assessments = [
  {
    title: 'JavaScript Basics Check',
    slug: 'javascript-basics-check',
    skill: 'JavaScript',
    description: 'A quick check of your foundational JavaScript knowledge.',
    questions: [
      { question_text: 'Which keyword declares a block-scoped variable in JavaScript?', options: ['var', 'let', 'global', 'define'], correct_option_index: 1 },
      { question_text: 'What does "===" check in JavaScript?', options: ['Value only', 'Type only', 'Value and type', 'Nothing'], correct_option_index: 2 },
      { question_text: 'Which method adds an item to the end of an array?', options: ['push()', 'pop()', 'shift()', 'concat()'], correct_option_index: 0 },
      { question_text: 'What is the result of typeof undefined?', options: ['"object"', '"undefined"', '"null"', '"function"'], correct_option_index: 1 },
      { question_text: 'Which of these is used to handle asynchronous code?', options: ['for loop', 'switch', 'Promise', 'array'], correct_option_index: 2 },
    ],
  },
  {
    title: 'Python Fundamentals Check',
    slug: 'python-fundamentals-check',
    skill: 'Python',
    description: 'Assess your baseline understanding of Python before starting the AI/ML path.',
    questions: [
      { question_text: 'Which symbol is used for comments in Python?', options: ['//', '#', '<!-- -->', '**'], correct_option_index: 1 },
      { question_text: 'What data type is returned by input()?', options: ['int', 'float', 'str', 'bool'], correct_option_index: 2 },
      { question_text: 'Which library is commonly used for numerical computing?', options: ['NumPy', 'React', 'Express', 'Figma'], correct_option_index: 0 },
      { question_text: 'How do you define a function in Python?', options: ['function foo():', 'def foo():', 'func foo():', 'lambda foo():'], correct_option_index: 1 },
      { question_text: 'Which of these is a mutable data structure?', options: ['tuple', 'string', 'list', 'int'], correct_option_index: 2 },
    ],
  },
  {
    title: 'UX Design Fundamentals Check',
    slug: 'ux-design-fundamentals-check',
    skill: 'UX Design',
    description: 'Check your foundational understanding of UX design concepts.',
    questions: [
      { question_text: 'What is the primary goal of user research?', options: ['Making the UI colorful', 'Understanding user needs and behavior', 'Writing code faster', 'Choosing fonts'], correct_option_index: 1 },
      { question_text: 'What is a wireframe?', options: ['A final visual design', 'A low-fidelity layout structure', 'A marketing document', 'A database schema'], correct_option_index: 1 },
      { question_text: 'What does usability testing measure?', options: ['Server response time', 'How easily users complete tasks', 'Code quality', 'SEO ranking'], correct_option_index: 1 },
      { question_text: 'What is a persona in UX design?', options: ['A code library', 'A fictional representation of a user segment', 'A color palette', 'A database table'], correct_option_index: 1 },
      { question_text: 'What is the purpose of a design system?', options: ['To slow down development', 'To ensure visual and functional consistency', 'To replace user research', 'To generate marketing copy'], correct_option_index: 1 },
    ],
  },
  {
    title: 'SQL Basics Check',
    slug: 'sql-basics-check',
    skill: 'SQL',
    description: 'Test your baseline SQL knowledge before diving into data analytics.',
    questions: [
      { question_text: 'Which statement retrieves data from a table?', options: ['GET', 'SELECT', 'FETCH', 'PULL'], correct_option_index: 1 },
      { question_text: 'Which clause filters rows before aggregation?', options: ['HAVING', 'WHERE', 'GROUP BY', 'ORDER BY'], correct_option_index: 1 },
      { question_text: 'Which keyword combines rows from two tables based on a related column?', options: ['MERGE', 'JOIN', 'UNION', 'LINK'], correct_option_index: 1 },
      { question_text: 'Which function counts the number of rows?', options: ['SUM()', 'COUNT()', 'TOTAL()', 'ADD()'], correct_option_index: 1 },
      { question_text: 'What does a PRIMARY KEY guarantee?', options: ['Fast queries always', 'Uniqueness of the column value', 'Automatic backups', 'Data encryption'], correct_option_index: 1 },
    ],
  },
  {
    title: 'Digital Marketing Basics Check',
    slug: 'digital-marketing-basics-check',
    skill: 'Marketing',
    description: 'Assess your baseline understanding of digital marketing concepts.',
    questions: [
      { question_text: 'What does SEO stand for?', options: ['Search Engine Optimization', 'Site Element Order', 'Social Engagement Output', 'Search Engagement Objective'], correct_option_index: 0 },
      { question_text: 'What is a conversion in digital marketing?', options: ['A page view', 'A desired user action, like a purchase', 'A social media follow only', 'An email sent'], correct_option_index: 1 },
      { question_text: 'What is A/B testing used for?', options: ['Comparing two versions to see which performs better', 'Backing up data', 'Encrypting emails', 'Building a website'], correct_option_index: 0 },
      { question_text: 'What does CTR stand for?', options: ['Content Transfer Rate', 'Click-Through Rate', 'Customer Trust Rating', 'Campaign Total Revenue'], correct_option_index: 1 },
      { question_text: 'Which channel is typically used for nurturing leads over time?', options: ['Email marketing', 'Billboard ads', 'Print flyers', 'Cold calling'], correct_option_index: 0 },
    ],
  },
];
